const By = [
    {
        "title": "By",
        "eng": "bestead by enemies (with dangers)",
        "rus": "окружённый врагами (опасностями)",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "brush by",
        "rus": "прошмыгнуть мимо",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "come by",
        "rus": "проходить мимо / доставать, достигать / заходить",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "do by",
        "rus": "обращаться",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "fast by / beside ",
        "rus": "совсем рядом",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "stand fast!",
        "rus": "стой!",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "get by",
        "rus": "проходить, проезжать / сдать (экзамен) / выходить сухим из воды / сводить концы с концами / устраиваться",
        "explanation_eng": 'theres enough room for the car to get by',
        "explanation_rus": "автомобиль вполне может здесь проехать",
    },
    {
        "title": "By",
        "eng": "go by",
        "rus": "проходить (о времени) / проходить мимо / судить по / руководствоваться ",
        "explanation_eng": 'I go by the barometer',
        "explanation_rus": 'Я руководствуюсь барометром',
    },
    {
        "title": "By",
        "eng": "hold by",
        "rus": "держаться (решения) / слушаться (совета)",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "lay by",
        "rus": "откладывать",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "let by",
        "rus": "пропустить",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "lie by",
        "rus": "оставаться без употребления / бездействовать / отдыхать",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "overcome by / with drink ",
        "rus": "пьяный",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "pass by",
        "rus": "проходить мимо / оставлять без внимания / пропускать",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "roll by / roll set by ",
        "rus": "откладывать / приберегать",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "slip by",
        "rus": "бежать (о времени)",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "stand by",
        "rus": "присутствовать / быть безучастным зрителем / защищать, помогать, поддерживать",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "steal by",
        "rus": "проскользнуть мимо",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "stop by",
        "rus": "заглянуть, зайти",
        "explanation_eng": null,
        "explanation_rus": null,
    },
    {
        "title": "By",
        "eng": "swear by",
        "rus": "клясться чем-л. / _разг. постоянно обращаться к чему-л. / рекомендовать что-л. / безгранично верить чему-л.",
        "explanation_eng": 'He swears by quinine for malaria',
        "explanation_rus": 'Он очень рекомендует принимать хинин от малярии',
    },
];

export default By;