const Up = [
    {"title": "Up",
        "eng": "back up",
        "rus": "поддерживать; давать задний ход",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "ball up",
        "rus": "_жарг. приводить в смущение; путать; провалиться на экзамене",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "bang up",
        "rus": "избить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "be up",
        "rus": "закончиться; встать, подняться; повыситься в цене; произойти;",
        "explanation_eng": "be up to smth / how are you",
        "explanation_rus":  "замышлять что-л / здравствуйте!, как вы поживаете?"
    },
    {"title": "Up",
        "eng": "bear up",
        "rus": "поддерживать; подбадривать; держаться стойко; спускаться (по ветру);  ",
        "explanation_eng": "to bear up for",
        "explanation_rus": "взять направление на"
    },
    {"title": "Up",
        "eng": "beat up",
        "rus": "взбивать (яйца и т.п.); вербовать (рекрутов); избивать;посещать; _мор. продвигаться против ветра, против течения",
        "explanation_eng": "beat up the quarters of",
        "explanation_rus": "обходиться со зверской жестокостью"
    },
    {"title": "Up",
        "eng": "bind up",
        "rus": "перевязывать (раны); переплетать в общий переплёт; связывать;  ",
        "explanation_eng": "this problem is bound up with many others",
        "explanation_rus": "эта проблема связана со многими другими"
    },
    {"title": "Up",
        "eng": "blaze up",
        "rus": "вспыхнуть",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "blow up",
        "rus": "раздувать; взрывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "bob up",
        "rus": "появляться на поверхности, всплывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "bomb up",
        "rus": "_ав. грузить (-ся) бомбами",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "bone up (on a subject)",
        "rus": " зубрить, долбить (предмет)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "bottle up",
        "rus": "сдерживать, скрывать (обиду и т.п.)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "bound up with",
        "rus": "тесно связанный с кем-л., чем-л.",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "box up",
        "rus": "втискивать, запихивать; неумелыми действиями портить, путать дело; вносить беспорядок",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "brace up",
        "rus": "подбадривать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "break up",
        "rus": "разбивать (на мелкие куски)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "breeze up",
        "rus": "крепчать (о ветре)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "bridle up",
        "rus": "задирать нос, важничать; выражать негодование",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "bring up",
        "rus": "приводить, приносить наверх; вскармливать, воспитывать; поднимать (вопрос); заводить (разговор); делать известным; привлекать к суду; _разг. вырвать, стошнить; увеличивать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "brush up",
        "rus": "чистить(ся); приводить (себя) в порядок; освежать (знания)",
        "explanation_eng": "I must brush up my French",
        "explanation_rus": "мне нужно освежить в памяти французский язык"
    },
    {"title": "Up",
        "eng": "buck up",
        "rus": "встряхнуться, оживиться, проявить энергию; спешить",
        "explanation_eng": "much bucked",
        "explanation_rus": "довольный, оживлённый"
    },
    {"title": "Up",
        "eng": "buckle up",
        "rus": "коробиться",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "build up",
        "rus": "воздвигать; постепенно создавать, строить; укреплять (здоровье); закладывать кирпичом (окно, дверь); застраивать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "bulb up",
        "rus": "завиваться (о кочане капусты)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "bulk up",
        "rus": "составлять изрядную сумму; доходить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "burn up",
        "rus": "зажигать; сжигать; _жарг. вспылить; рассвирепеть",
        "explanation_eng": "she has money to burn",
        "explanation_rus": "у неё денег куры не клюют"
    },
    {"title": "Up",
        "eng": "burst up",
        "rus": "взорваться; _разг. потерпеть неудачу, крушение",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "button up",
        "rus": "застегнуть(ся) на все пуговицы; _воен. приводить в порядок войска; закрыть(ся), запереть(ся) (внутри помещения)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "buy up",
        "rus": "скупать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "call up",
        "rus": "звать наверх; призывать (на военную службу); вызывать (по телефону); вызывать в памяти; представлять на рассмотрение (законопроект и т.п.)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "catch up",
        "rus": "поднять; подхватить (тж. _перен. напр. новое слово); догнать;  ; прервать; _ам. приготовить лошадей (для путешественников)",
        "explanation_eng": "we had caught up on sleep",
        "explanation_rus": "нам удалось отоспаться"
    },
    {"title": "Up",
        "eng": "chalk up",
        "rus": "вести счёт (в игре)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "chaw up",
        "rus": "разбить наголову (врага, противника в игре); разбить вдребезги",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "check up",
        "rus": "проверять",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "cheer up",
        "rus": "утешить(ся); ободрить(ся)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "chock up",
        "rus": "забить, загромоздить, заставить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "choke up",
        "rus": "засорять; заглушать (сорными травами); заносить (реку песком);",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "chuck up",
        "rus": "бросать (дело, службу и т.п.)",
        "explanation_eng": "chuck it!",
        "explanation_rus": "молчи!; перестань!"
    },
    {"title": "Up",
        "eng": "chunk up",
        "rus": "подбросить топлива (в огонь); набрать топлива",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "clean up",
        "rus": "прибирать, приводить в порядок; заканчивать начатую работу; _жарг. сорвать большой куш",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "clear up",
        "rus": "прибирать, убирать; выяснять; распутывать (дело); проясняться (о погоде)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "close up",
        "rus": "закрывать; ликвидировать; закрываться (о ране); заканчивать; сомкнуть ряды",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "cocker up (in)",
        "rus": "потворствовать ; закармливать сладостями",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "come up",
        "rus": "подниматься, вырастать, возникать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "cotton up",
        "rus": "стараться расположить к себе",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "cough up / out",
        "rus": "сболтнуть, проболтаться, выдать (что-л.); выжать из себя",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "cover up",
        "rus": "спрятать, тщательно прикрыть",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "crack up",
        "rus": "_разг. а> превозносить; рекламировать; б> разбиваться (вдребезги); разрушаться; потерпеть аварию (о самолёте); вызвать аварию (самолёта); в> стареть; слабеть (от старости)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "crop up",
        "rus": "а> неожиданно обнаруживаться; возникать; б> размельчить, растолочь, смять",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "cry up",
        "rus": "превозносить, прославлять;  _",
        "explanation_eng": "there's no use to cry (crying) over spilt milk",
        "explanation_rus": "посл. сделанного, потерянного не воротишь"
    },
    {"title": "Up",
        "eng": "curl up",
        "rus": "а> скручивать(ся), сморщивать(ся); б> _разг. скрутить (о несчастье, горе и т.п.); в> испытать потрясение",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "cut up",
        "rus": "а> разрубать, разрезать на куски; б> раскритиковать; в> подрывать (силы, здоровье); причинять страдания; be cut up мучиться, страдать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "deliver up",
        "rus": "сдавать (крепость и т.п.)",
        "explanation_eng": "to deliver the goods",
        "explanation_rus": "выполнить взятые на себя обязательства"
    },
    {"title": "Up",
        "eng": "dig up",
        "rus": "а> вырыть; _перен. выкопать, разыскать; б> поднять целину; в> _ам. _разг. сделать взнос; наскрести определённую сумму; г> _ам. _разг. получить (деньги)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "dish up",
        "rus": "а> подавать кушанье к столу; сервировать; _перен. уметь преподнести (анекдот и т.п.); б> _разг. мыть посуду",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "do up",
        "rus": "приводить в порядок, прибирать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "double up",
        "rus": "скрючить(ся); сгибаться",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "drag up",
        "rus": "_разг. плохо воспитывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "draw up",
        "rus": "а> составлять (документ); б> останавливаться;  э; в> _refl. подтянуться; выпрямиться; г> _воен. выстраивать(ся)",
        "explanation_eng": "the carriage drew up before the door",
        "explanation_rus": "кипаж остановился у подъезда",
    },
    {"title": "Up",
        "eng": "dream up",
        "rus": "_разг. выдумывать, фантазировать; придумывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "dress up",
        "rus": "а> изысканно одевать(ся); б> надевать маскарадный костюм",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "drink up",
        "rus": "а> = drink down; б> выпить до дна;  ",
        "explanation_eng": "I could drink the sea dry",
        "explanation_rus": "меня мучит жажда, я очень хочу пить"
    },
    {"title": "Up",
        "eng": "drive up",
        "rus": "подъехать, подкатить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "drum up",
        "rus": "созывать, зазывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "dry up",
        "rus": "а> высушивать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "eat up",
        "rus": "а> пожирать; поглощать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "face up",
        "rus": "а> примириться с чем-л. неприятным (to); б> быть готовым встретить (to)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "fasten up",
        "rus": "закрывать; завязывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "feed up",
        "rus": "откармливать, усиленно питать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "feel up to",
        "rus": "быть в состоянии",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "fetch up",
        "rus": "а> рвать, блевать;б> нагонять, навёрстывать; в> останавливаться; г> довершать, заканчивать",
        "explanation_eng": "he fetches up / to fetch up against smth. ",
        "explanation_rus": "его рвёт / стукнуться обо что-л"
    },
    {"title": "Up",
        "eng": "figure up",
        "rus": "подсчитывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "fill up",
        "rus": "а> наполнять(ся); набивать; заполнять (вакансию); б> возмещать (недостающее)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "fire up",
        "rus": "вспылить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "fish up",
        "rus": "вытаскивать (из воды)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "fit up",
        "rus": "а> отделывать; б> снабжать; оснащать; в> собирать, монтировать",
        "explanation_eng": "the hotel is fitted up with all modern conveniences",
        "explanation_rus": "гостиница имеет все (современные) удобства"
    },
    {"title": "Up",
        "eng": "fix up",
        "rus": "_разг. а> устроить, дать приют; б> решить; в> организовать; устранить препятствия; г> уладить; привести в порядок; урегулировать; договориться; д> починить; подправить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "flare up",
        "rus": "а> вспыхнуть; б> разразиться гневом, вспылить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "fold up",
        "rus": "а> свёртывать, завёртывать; б> _разг. свернуться",
        "explanation_eng": "the business finally folded up last week",
        "explanation_rus": "предприятие, в конце концов, на прошлой неделе прекратило существование"
    },
    {"title": "Up",
        "eng": "follow up",
        "rus": "а> преследовать упорно, энергично (тж. _перен.); б> доводить до конца; развивать, завершать;  ",
        "explanation_eng": "the letter reads as follows",
        "explanation_rus": "в письме говорится следующее"
    },
    {"title": "Up",
        "eng": "fork up",
        "rus": "= fork frame up _разг. подстраивать (что-л.); подтасовывать факты; судить на основании сфабрикованных обвинений",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "frizz up",
        "rus": "виться",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "furbish up",
        "rus": "подновлять, ремонтировать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "fuss up",
        "rus": "_ам. _разг. наряжать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "gather up",
        "rus": "а> подбирать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "gear up",
        "rus": "ускорять (движение и т.п.)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "get up",
        "rus": "а> вставать, подниматься (тж. на гору); б> садиться (в экипаж, на лошадь); в> усиливаться (о пожаре, ветре, буре); г> дорожать (о товарах); д> подготавливать, осуществлять; оформлять (книгу); ставить (пьесу); е> гримировать, наряжать; причёсывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "give up",
        "rus": "а> оставить, отказаться (от работы и т.п.);  ; б> бросить (привычку); в> уступить",
        "explanation_eng": "he is given up by the doctors",
        "explanation_rus": "он признан врачами безнадёжным"
    },
    {"title": "Up",
        "eng": "go up in smoke",
        "rus": " a> улетучиться; б> расти (о числе); повышаться (о ценах); ; в> взорваться, сгореть; г> _ам. разориться",
        "explanation_eng": "apples have gone up",
        "explanation_rus": "a яблоки подорожали"
    },
    {"title": "Up",
        "eng": "grind up",
        "rus": "измельчать, размалывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "grow up",
        "rus": "а> ссозревать; становиться взрослым; б> создаваться, возникать (об обычаях)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "hand up",
        "rus": "подавать снизу вверх",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "hang up",
        "rus": "а> повесить что-л.; повесить телефонную трубку, дать отбой; б> медлить, откладывать, оставлять нерешённым; в> _разг. закладывать; отдавать в залог",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "haul up",
        "rus": "а> поднимать; б> останавливаться; в> отчитывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "help up",
        "rus": "помочь встать, подняться, поддержать кого-л.",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "hold up",
        "rus": "а> выставлять, показывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "hole up",
        "rus": "а> быть в зимней спячке; б> отсиживаться, прятаться от людей",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "hush up",
        "rus": "замалчивать, скрывать; замять",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "ice up",
        "rus": "обледенеть",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "jack up",
        "rus": "а> бросить, оставить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "jazz up",
        "rus": "подбадривать, действовать возбуждающе",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "jump up",
        "rus": "вскакивать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "keep up with smb.",
        "rus": "держаться наравне с кем-л., не отставать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "key up",
        "rus": "а> возбуждать, взвинчивать (кого-л.); б> придавать решимость, смелость; в> повышать (спрос и т.п.)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "kick up",
        "rus": "а> швырять вверх ударом ноги; поднимать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "knit up",
        "rus": "связывать; поднимать спущенные петли; штопать; _перен. заключать, заканчивать (спор и т.п.)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "knock up",
        "rus": "а> ударом подбросить вверх; б> поднять, разбудить стуком; в> утомлять; ослаблять",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "lay up",
        "rus": "а> откладывать, копить; б> возводить, сооружать; в> выводить временно из строя",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "lead up to",
        "rus": "а> постепенно подготовлять; б> наводить разговор на что-л.",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "let up",
        "rus": "а> ослабевать; б> прекращать, оставлять",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "lie up",
        "rus": "а> лежать, не выходить из комнаты (из-за недомогания); б> стоять в стороне, отстраняться; в> _мор. стоять в доке",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "limber up",
        "rus": "_спорт. делать разминку",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "line up",
        "rus": "а> строить(ся), выстраивать(ся) (в линию)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "live up to",
        "rus": "жить согласно (принципам и т.п.); быть достойным (чего-л.)",
        "explanation_eng": "as I live by bread!, as I live and breathe!",
        "explanation_rus": "честное слово!"
    },
    {"title": "Up",
        "eng": "load up",
        "rus": "а> грузиться; б> наедаться; напиваться",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "lock up",
        "rus": "а> запирать; б> сажать в тюрьму; заключать в сумасшедший дом; в> вложить капитал в трудно реализуемые бумаги; г> утаивать (факты, сведения)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "look up",
        "rus": "а> смотреть вверх, поднимать глаза",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "loosen up",
        "rus": "а> делать более гибкими (мышцы); б> становиться более разговорчивым, менее застенчивым",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "make up",
        "rus": "а> пополнять, возмещать, компенсировать; навёрстывать; б> составлять, собирать; комплектовать; в> гримировать(ся); г> подкраситься, подмазаться; д> выдумывать; е> устраивать, улаживать; ж> мириться;з> шить; кроить; и> _полигр. верстать; к> подходить, приближаться; л> подлизываться, подхалимничать",
        "explanation_eng": "let us make it up",
        "explanation_rus": "давайте забудем это, давайте помиримся"
    },
    {"title": "Up",
        "eng": "mark up",
        "rus": "а> повысить цену; б> вести счёт",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "measure up (to; иногда тж. with)",
        "rus": "а> достигать (уровня); б> соответствовать, отвечать (требованиям); в> оправдывать (надежды)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "mew up",
        "rus": "заключать в тюрьму; запирать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "mix up",
        "rus": "а> хорошо перемешивать; б> спутать, перепутать; в> впутывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "mock up",
        "rus": "_разг. импровизировать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "mop up",
        "rus": "а> вытирать; осушать; б> _разг. поглощать (пищу); в> _разг. приканчивать, убивать; разделаться; г> _воен. очищать (захваченную территорию от противника)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "move up",
        "rus": "пододвинуть",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "mushroom up",
        "rus": "а> расти как грибы; б> быстро распространяться",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "muster up",
        "rus": "собирать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "nail up",
        "rus": "заколачивать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "nose up",
        "rus": "_ав. задирать нос (самолёта)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "open up",
        "rus": "а> сделать(ся) доступным; раскрывать(ся); обнаруживаться",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "own up",
        "rus": "_разг. а> откровенно признаваться; б> безропотно подчиняться",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "pack up",
        "rus": "_разг. а> упаковывать(ся); б> прекращать (работу и т.п.); в> испортиться, выйти из строя (о механизме); г> умереть",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "parch up",
        "rus": "высыхать, сохнуть",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "pass up",
        "rus": "_ам. отказываться (от чего-л.); отвергать (что-л.) ",
        "explanation_eng": "to pass by the name of...",
        "explanation_rus": "быть известным под именем..., называться..."
    },
    {"title": "Up",
        "eng": "paste up",
        "rus": "расклеивать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "patch up",
        "rus": "а> чинить на скорую руку; заделывать; подправлять; б> улаживать (ссору); в> делать что-л. небрежно",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "pay up",
        "rus": "а> выплачивать сполна (недоимку и т.п.) б> выплачивать вовремя",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "pick up",
        "rus": "а> разрыхлять (киркой); б> поднимать, подбирать; в> заезжать за кем-л.;г> приобретать",
        "explanation_eng": "I'll pick you up at five o'clock",
        "explanation_rus": "я заеду за вами в пять часов"
    },
    {"title": "Up",
        "eng": "piece up",
        "rus": "чинить, латать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "pile up",
        "rus": "а> нагромождать(ся); б> накапливать; в> разбить автомашину; г> _ав. разбить самолёт при взлёте или посадке; д> наскочить на мель (о корабле)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "pipe up",
        "rus": "заиграть; запеть; заговорить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "play up to",
        "rus": "подыгрывать; _перен. подлизываться",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "plough up",
        "rus": "а> взрывать (землю); б> распахивать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "plug up",
        "rus": "закупоривать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "plunge up",
        "rus": "круто подниматься (о дороге и т.п.)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "poke up",
        "rus": "а> совать, пихать; толкать; б> _разг. запирать (в тесном помещении)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "pop up",
        "rus": "неожиданно возникнуть",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "preach up",
        "rus": "восхвалять",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "puff up /  puffed up",
        "rus": "а> подниматься клубами (о дыме и т.п.); б> самодовольный, полный самомнения",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "pull up",
        "rus": "а> останавливать(ся); б> сдерживаться",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "pump up",
        "rus": "накачивать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "rake up",
        "rus": "сгребать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "read up",
        "rus": "специально изучать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "reckon up",
        "rus": "подсчитывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "rein up",
        "rus": "а> останавливать(ся); б> остановить, осадить (лошадь)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "rev up",
        "rus": "увеличивать скорость, число оборотов; давать газ",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "rig up",
        "rus": "снаряжать или строить наспех, из чего попало",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "ring up",
        "rus": "а> разбудить звонком; б> звонить, вызывать по телефону;",
        "explanation_eng": "to ring the curtain up",
        "explanation_rus": "дать звонок к поднятию занавеса"
    },
    {"title": "Up",
        "eng": "rip up",
        "rus": "а> распарывать; б> вскрывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "roll up",
        "rus": "а> скатывать; свёртывать(ся); завёртывать; б> _разг. появиться внезапно, заявиться; в> _воен. атаковать фланги; расширять участок прорыва",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "rough up",
        "rus": "_ам. _разг. избивать (кого-л.)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "round up",
        "rus": "а> сгонять (скот); б> окружать, производить облаву",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "rub up",
        "rus": "_ам. _разг. избивать (кого-л.)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "run up",
        "rus": "а> съездить (в город); б> быстро расти; увеличиваться; в> поднимать(ся); г> вздувать (цены); д> доходить (to run до); е> складывать (столбец цифр); ж> возводить спешно (постройку)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "save up",
        "rus": "делать сбережения; копить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "screw up",
        "rus": "а> завинчивать; подвинчивать (болт, гайку и т.п.); навинчивать (крышку и т.п.); б> подтягивать, укреплять",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "sell up",
        "rus": "продавать с торгов",
        "explanation_eng": "I'm not sold on this",
        "explanation_rus": "я от того отнюдь не в восторге"
    },
    {"title": "Up",
        "eng": "send up",
        "rus": "а> направлять вверх; б> _ам. _жарг. приговорить к тюремному заключению",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "set up for",
        "rus": "выдавать себя за кого-л.",
        "explanation_eng": "he sets up for a scholar",
        "explanation_rus": "он претендует на учёность"
    },
    {"title": "Up",
        "eng": "sew up",
        "rus": "а> зашивать; б> _разг. полностью контролировать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "shake up",
        "rus": "а> встряхивать; взбалтывать; б> _перен. расшевелить; в> раздражать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "shoot up",
        "rus": "а> быстро расти; б> взлетать, вздыматься (о пламени и т.п.); в> _воен. расстрелять; разбить огнём; г> _ам. _разг. терроризировать (жителей) стрельбой",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "show up",
        "rus": "а> изобличать; разоблачать; б> выделяться (на фоне); в> _разг. появляться; объявиться неожиданно",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "shut up",
        "rus": "а> забить, заколотить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "sign up = sign sit up",
        "rus": "а> приподняться, сесть (в постели); б> не ложиться спать; засиживаться до поздней ночи; бодрствовать; в> сидеть прямо; выпрямиться;",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "size up",
        "rus": "а> определять размер, величину; б> _разг. составить мнение (о ком-л.)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "slack up",
        "rus": "замедлять ход",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "slip up",
        "rus": "а> споткнуться; б> _разг. совершить ошибку",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "smash up",
        "rus": "разбивать(ся) вдребезги",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "snap up",
        "rus": "а> подхватить, перехватить; б> резко остановить, перебить (говорящего)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "soften up",
        "rus": "_воен. обрабатывать (оборону) артогнём",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "soup up",
        "rus": "а> увеличивать мощность (двигателя и т.п.); б> увеличивать скорость (самолёта, ракеты и т.п.); в> придавать силу, живость",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "speak up",
        "rus": "а> говорить громко и отчётливо; б> высказаться; so to speak так сказать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "split up",
        "rus": "разделять(ся), раскалывать(ся)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "sponge up",
        "rus": "впитывать губкой",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "spring up",
        "rus": "возникать (об обычае, городах и т.п.), появляться",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "square up",
        "rus": "а> расплатиться, урегулировать расчёты (с кем-л.); б> изготовиться к бою (о боксёре)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "stake up",
        "rus": "загораживать кольями",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "stake up",
        "rus": "загораживать кольями",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "stand up to",
        "rus": "а> смело встречать; быть на высоте; б> перечить, прекословить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "start up",
        "rus": "а> вскакивать; б> появляться; в> пускать в ход",
        "explanation_eng": "a new idea has started up",
        "explanation_rus": "возникла новая идея"
    },
    {"title": "Up",
        "eng": "stay up",
        "rus": "не ложиться спать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "steal up",
        "rus": "подкрасться",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "step up",
        "rus": "а> подойти; б> продвигать; выдвигать; в> увеличивать; ускорять; г> _эл. повышать напряжение",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "stick up to",
        "rus": "не подчиняться; оказывать сопротивление;",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "stir up",
        "rus": "а> хорошенько размешивать, взбалтывать; б> возбуждать (любопытство и т.п.); в> раздувать (ссору);",
        "explanation_eng": "not to stir an eyelid / not to stir a finger",
        "explanation_rus": "глазом не моргнуть / пальцем не пошевелить"
    },
    {"title": "Up",
        "eng": "stitch up",
        "rus": "а> зашивать; б> _полигр. брошюровать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "stop up",
        "rus": "а> затыкать, заделывать; б> _разг. не ложиться спать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "strike up",
        "rus": "начинать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "string up",
        "rus": "а> взвинчивать, напрягать (нервы и т.п.); б> _разг. вздёрнуть, повесить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "study up",
        "rus": "готовиться к экзамену",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "stump up",
        "rus": "_жарг. выкладывать деньги, платить; расплачиваться",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "suck up",
        "rus": "а> всасывать; поглощать; б> _школ. _жарг. подлизываться (to)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "sum up",
        "rus": "резюмировать, суммировать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "take up",
        "rus": "а> обсуждать (план и т.п.); б> поднимать; в> занимать, принимать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "talk up",
        "rus": "а> хвалить, расхваливать; б> говорить прямо и откровенно",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "tape up",
        "rus": "бинтовать, забинтовывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "tear up",
        "rus": "а> вырвать; б> изорвать",
        "explanation_eng": "a tree torn up by the roots",
        "explanation_rus": "дерево, вырванное с корнем"
    },
    {"title": "Up",
        "eng": "tee up",
        "rus": "= tee think up _ам. выдумать, сочинить, придумать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "throw up",
        "rus": "а> подбрасывать; б> вскидывать (глаза); поднимать (руки); в> возводить, быстро строить (дом, баррикады); г> выделять, оттенять; д> бросать, отказываться от участия;",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "tie up",
        "rus": "а> привязать; перевязать; связать; б> ограничить свободу действий; мешать, препятствовать",
        "explanation_eng": "I don't tie it up",
        "explanation_rus": "это не вызывает у меня никаких ассоциаций, воспоминаний"
    },
    {"title": "Up",
        "eng": "tone up",
        "rus": "а> усиливать, повышать тон (чего-л.); б> тонизировать, повышать тонус",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "tool up",
        "rus": "оборудовать (инструментами, станками фабрику и т.п.)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "top up",
        "rus": "доливать, досыпать (доверху)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "touch up",
        "rus": "а> исправлять, заканчивать, отделывать, класть последние штрихи, мазки; б> подстегнуть (лошадь); в> напомнить, натолкнуть; г> взволновать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "tuck up",
        "rus": "а> засучивать (рукава); подбирать (подол); б> _жарг. вешать (преступника)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "tune up",
        "rus": "а> настраивать инструменты; б> наладить, отрегулировать машину; в> запеть, заиграть; г> _шутл. заплакать (о ребёнке)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "turn up",
        "rus": "а> поднимать(ся) вверх; загибать(ся); her nose turns up у неё вздёрнутый нос; б> внезапно появляться; приходить, приезжать; в> случаться; подвернуться, оказаться;г> вскапывать, выкапывать; д> открыть (карту); е> _разг. вызывать тошноту;",
        "explanation_eng": "something will turn up / to turn up the radio ",
        "explanation_rus": "что-нибудь да подвернётся / сделать радио громче "
    },
    {"title": "Up",
        "eng": "twist up",
        "rus": "скручивать (в трубочку)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "wait up",
        "rus": "_разг. не ложиться спать (до чьего-л. прихода - for)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "walk up",
        "rus": "подойти (to walk к кому-л.)",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "wall up",
        "rus": "заделывать (дверь, окно); замуровывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "warm up",
        "rus": "а> разогревать(ся), подогревать(ся); б> воодушевлять(ся); разжигать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "wash up",
        "rus": "мыть посуду",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "weigh up",
        "rus": "а> уравновешивать; б> взвесить и решить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "whip up",
        "rus": "а> подстёгивать; подгонять; б> взбивать; в> расшевелить",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "whistle up",
        "rus": "вызывать, подзывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "wind up",
        "rus": "а> сматывать; б> заводить (часы); в> заводиться;  ; теперь его не остановишь;",
        "explanation_eng": "I'm afraid he's wound up",
        "explanation_rus": "ну, он теперь завёлся (на час)"
    },
    {"title": "Up",
        "eng": "wipe up",
        "rus": "подтирать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "work up / wrought",
        "rus": " а> разрабатывать; б> отделывать, придавать законченный вид; в> возбуждать, вызывать",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "wrap up",
        "rus": "а> кутаться; б> завершать; давать краткое заключение",
        "explanation_eng": null,
        "explanation_rus": null
    },
    {"title": "Up",
        "eng": "yield up",
        "rus": "а> отказываться от; б> сдаваться; в> сдавать, уступая силе",
        "explanation_eng": null,
        "explanation_rus": null
    }
]

export default Up;